import { FactCard, Resource } from "../types";

export const programmingResources: Resource[] = [
  {
    id: "1",
    name: "React",
    url: "https://reactjs.org/docs/getting-started.html",
    category: "Frameworks",
    description:
      "UI library by Meta for building fast and interactive frontend apps.",
  },
  {
    id: "2",
    name: "JavaScript",
    url: "https://developer.mozilla.org/en-US/docs/Web/JavaScript",
    category: "Languages",
    description:
      "The language of the web — used for both frontend and backend development.",
  },
  {
    id: "3",
    name: "Git",
    url: "https://git-scm.com/doc",
    category: "Tools",
    description:
      "Version control system for tracking changes and collaborating on code.",
  },
  {
    id: "4",
    name: "Next.js",
    url: "https://nextjs.org/docs",
    category: "Frameworks",
    description:
      "React framework for SSR, SSG, and full-stack web apps with zero config.",
  },
  {
    id: "5",
    name: "Python",
    url: "https://docs.python.org/3/",
    category: "Languages",
    description:
      "Beginner-friendly, versatile language for AI, web, and automation.",
  },
  {
    id: "6",
    name: "MongoDB",
    url: "https://www.mongodb.com/docs/",
    category: "Database",
    description: "NoSQL database for flexible, document-oriented data storage.",
  },
  {
    id: "7",
    name: "Docker",
    url: "https://docs.docker.com/",
    category: "Tools",
    description:
      "Container platform for building, shipping, and running applications anywhere.",
  },
  {
    id: "8",
    name: "TensorFlow",
    url: "https://www.tensorflow.org/learn",
    category: "AI/ML",
    description:
      "Open-source machine learning framework by Google for deep learning models.",
  },
  {
    id: "9",
    name: "Tailwind CSS",
    url: "https://tailwindcss.com/docs",
    category: "CSS Frameworks",
    description:
      "Utility-first CSS framework for fast and customizable styling.",
  },
  {
    id: "10",
    name: "TypeScript",
    url: "https://www.typescriptlang.org/docs/",
    category: "Languages",
    description:
      "A superset of JavaScript adding static types for cleaner, safer code.",
  },
  {
    id: "11",
    name: "PostgreSQL",
    url: "https://www.postgresql.org/docs/",
    category: "Database",
    description:
      "Powerful open-source SQL database known for reliability and advanced features.",
  },
  {
    id: "12",
    name: "Firebase",
    url: "https://firebase.google.com/docs",
    category: "Database",
    description:
      "Google’s real-time NoSQL database with built-in auth, hosting, and analytics.",
  },
  {
    id: "13",
    name: "Flutter",
    url: "https://docs.flutter.dev/",
    category: "Mobile",
    description:
      "Google’s UI toolkit for building natively compiled mobile, web, and desktop apps.",
  },
  {
    id: "14",
    name: "AWS",
    url: "https://docs.aws.amazon.com/",
    category: "APIs & Cloud",
    description:
      "Amazon Web Services — a leading cloud platform for hosting and scaling applications.",
  },
  {
    id: "15",
    name: "Vue.js",
    url: "https://vuejs.org/guide/",
    category: "Frameworks",
    description:
      "Progressive JavaScript framework for building user interfaces with ease.",
  },
  {
    id: "16",
    name: "C++",
    url: "https://isocpp.org/",
    category: "Languages",
    description:
      "High-performance language often used in systems, game dev, and competitive programming.",
  },
  {
    id: "17",
    name: "GraphQL",
    url: "https://graphql.org/learn/",
    category: "APIs & Cloud",
    description:
      "A query language for APIs that gives clients the power to request exactly what they need.",
  },
  {
    id: "18",
    name: "Chakra UI",
    url: "https://chakra-ui.com/docs/getting-started",
    category: "CSS Frameworks",
    description:
      "Simple, accessible React component library for modern web apps.",
  },
  {
    id: "19",
    name: "MySQL",
    url: "https://dev.mysql.com/doc/",
    category: "Database",
    description:
      "Popular open-source relational database for web and enterprise applications.",
  },
  {
    id: "20",
    name: "Go",
    url: "https://golang.org/doc/",
    category: "Languages",
    description:
      "Fast, concurrent, and simple — built by Google for scalable backend systems.",
  },
  {
    id: "21",
    name: "Keras",
    url: "https://keras.io/getting_started/",
    category: "AI/ML",
    description:
      "High-level neural networks API built on TensorFlow for quick prototyping.",
  },
  {
    id: "22",
    name: "Azure",
    url: "https://learn.microsoft.com/en-us/azure/",
    category: "APIs & Cloud",
    description:
      "Microsoft’s cloud platform offering app hosting, databases, and AI services.",
  },
  {
    id: "23",
    name: "Bootstrap",
    url: "https://getbootstrap.com/docs/",
    category: "CSS Frameworks",
    description:
      "Popular frontend framework for building responsive, mobile-first websites.",
  },
  {
    id: "24",
    name: "Node.js",
    url: "https://nodejs.org/en/docs",
    category: "Frameworks",
    description:
      "JavaScript runtime built on Chrome’s V8 engine for backend and server-side apps.",
  },
  {
    id: "25",
    name: "Figma",
    url: "https://help.figma.com/hc/en-us",
    category: "Tools",
    description: "Collaborative design tool for UI/UX and prototyping.",
  },
  {
    id: "26",
    name: "Scikit-Learn",
    url: "https://scikit-learn.org/stable/user_guide.html",
    category: "AI/ML",
    description:
      "Python library for machine learning, featuring tools for data mining and analysis.",
  },
  {
    id: "27",
    name: "Linux Command Line",
    url: "https://linuxcommand.org/lc3_learning_the_shell.php",
    category: "Tools",
    description:
      "Learn essential shell commands to navigate and control Linux systems.",
  },
  {
    id: "28",
    name: "Material UI",
    url: "https://mui.com/material-ui/getting-started/",
    category: "CSS Frameworks",
    description:
      "React component library implementing Google’s Material Design system.",
  },
  {
    id: "29",
    name: "Django",
    url: "https://docs.djangoproject.com/",
    category: "Frameworks",
    description:
      "High-level Python framework that encourages clean, rapid web development.",
  },
  {
    id: "30",
    name: "Hugging Face",
    url: "https://huggingface.co/docs",
    category: "AI/ML",
    description:
      "Platform for NLP models and transformers, making AI accessible to developers.",
  },
  {
    id: "31",
    name: "Google Cloud",
    url: "https://cloud.google.com/docs",
    category: "APIs & Cloud",
    description:
      "Comprehensive cloud computing platform by Google for apps, storage, and ML.",
  },
  {
    id: "32",
    name: "Rust",
    url: "https://doc.rust-lang.org/book/",
    category: "Languages",
    description:
      "Memory-safe systems programming language loved for performance and reliability.",
  },
  {
    id: "33",
    name: "Redux Toolkit",
    url: "https://redux-toolkit.js.org/introduction/getting-started",
    category: "Frameworks",
    description:
      "Official, efficient Redux library for managing application state in React.",
  },
  {
    id: "34",
    name: "Postman",
    url: "https://learning.postman.com/",
    category: "Tools",
    description:
      "Tool for testing and managing APIs easily with a user-friendly interface.",
  },
  {
    id: "35",
    name: "Swift",
    url: "https://developer.apple.com/swift/",
    category: "Languages",
    description:
      "Apple’s programming language for building fast and safe iOS/macOS applications.",
  },
  {
    id: "36",
    name: "Vite",
    url: "https://vitejs.dev/guide/",
    category: "Tools",
    description:
      "Next-generation frontend build tool that’s fast and developer-friendly.",
  },
  {
    id: "37",
    name: "React Native",
    url: "https://reactnative.dev/docs/getting-started",
    category: "Mobile",
    description: "Build cross-platform mobile apps using React and JavaScript.",
  },
  {
    id: "38",
    name: "OpenAI API",
    url: "https://platform.openai.com/docs",
    category: "APIs & Cloud",
    description:
      "AI API for building apps powered by ChatGPT, DALL·E, and GPT models.",
  },
  {
    id: "39",
    name: "Bun",
    url: "https://bun.sh/docs",
    category: "Tools",
    description:
      "All-in-one JavaScript runtime, bundler, and test runner — faster alternative to Node.",
  },
  {
    id: "40",
    name: "LangChain",
    url: "https://js.langchain.com/docs/",
    category: "AI/ML",
    description:
      "Framework for building AI-powered applications using LLMs like GPT.",
  },
  {
    id: "41",
    name: "Redis",
    url: "https://redis.io/docs/",
    category: "Database",
    description:
      "In-memory key-value data store known for caching and real-time analytics.",
  },
  {
    id: "42",
    name: "GitHub Actions",
    url: "https://docs.github.com/en/actions",
    category: "Tools",
    description:
      "Automate workflows like build, test, and deployment directly from GitHub.",
  },
  {
    id: "43",
    name: "Numpy",
    url: "https://numpy.org/doc/",
    category: "AI/ML",
    description:
      "Core Python library for numerical computing and array manipulation.",
  },
  {
    id: "44",
    name: "Three.js",
    url: "https://threejs.org/docs/",
    category: "Frameworks",
    description:
      "JavaScript 3D library for creating WebGL-powered 3D graphics and animations.",
  },
  {
    id: "45",
    name: "Sass",
    url: "https://sass-lang.com/guide",
    category: "CSS Frameworks",
    description:
      "CSS preprocessor adding variables, nesting, and advanced styling features.",
  },
  {
    id: "46",
    name: "Prisma",
    url: "https://www.prisma.io/docs",
    category: "Database",
    description:
      "Next-generation ORM for Node.js and TypeScript for managing databases elegantly.",
  },
  {
    id: "47",
    name: "Render",
    url: "https://render.com/docs",
    category: "APIs & Cloud",
    description:
      "Modern cloud platform for deploying web apps, databases, and static sites easily.",
  },
  {
    id: "48",
    name: "Jest",
    url: "https://jestjs.io/docs/getting-started",
    category: "Tools",
    description:
      "Delightful JavaScript testing framework with a focus on simplicity.",
  },
  {
    id: "49",
    name: "Pandas",
    url: "https://pandas.pydata.org/docs/",
    category: "AI/ML",
    description: "Powerful Python library for data analysis and manipulation.",
  },
  {
    id: "50",
    name: "Supabase",
    url: "https://supabase.com/docs",
    category: "Database",
    description:
      "Open-source Firebase alternative with PostgreSQL at its core.",
  },
  {
    id: "51",
    name: "Netlify",
    url: "https://docs.netlify.com/",
    category: "APIs & Cloud",
    description:
      "Platform to deploy and scale frontend web apps with CI/CD built-in.",
  },
  {
    id: "52",
    name: "Heroku",
    url: "https://devcenter.heroku.com/categories/reference",
    category: "APIs & Cloud",
    description:
      "Cloud platform that lets developers deploy, manage, and scale apps easily.",
  },
  {
    id: "53",
    name: "NPM",
    url: "https://docs.npmjs.com/",
    category: "Tools",
    description:
      "Package manager for JavaScript used to install and manage dependencies.",
  },
  {
    id: "54",
    name: "ESLint",
    url: "https://eslint.org/docs/latest/",
    category: "Tools",
    description:
      "Linting utility for identifying and fixing code style and syntax issues in JS/TS.",
  },
  {
    id: "55",
    name: "Zustand",
    url: "https://docs.pmnd.rs/zustand/getting-started/introduction",
    category: "Frameworks",
    description:
      "Small, fast, and scalable state management library for React.",
  },
  {
    id: "56",
    name: "Svelte",
    url: "https://svelte.dev/docs",
    category: "Frameworks",
    description:
      "Compiler-based frontend framework for fast and reactive UI building.",
  },
  {
    id: "57",
    name: "Redux",
    url: "https://redux.js.org/",
    category: "Frameworks",
    description:
      "Predictable state container for JavaScript apps — especially with React.",
  },
  {
    id: "58",
    name: "C",
    url: "https://devdocs.io/c/",
    category: "Languages",
    description:
      "Foundational programming language that powers OS, kernels, and embedded systems.",
  },
  {
    id: "59",
    name: "Express.js",
    url: "https://expressjs.com/",
    category: "Frameworks",
    description:
      "Minimal Node.js web framework for building APIs and web servers.",
  },
  {
    id: "60",
    name: "OpenCV",
    url: "https://docs.opencv.org/",
    category: "AI/ML",
    description:
      "Library for computer vision and image processing in C++ and Python.",
  },
];

export const dsaProblems = [
  {
    id: "1",
    title: "Two Sum",
    difficulty: "Easy",
    leetcode: "https://leetcode.com/problems/two-sum/",
    category: "Arrays",
  },
  {
    id: "2",
    title: "Reverse Linked List",
    difficulty: "Easy",
    leetcode: "https://leetcode.com/problems/reverse-linked-list/",
    category: "Linked List",
  },
  {
    id: "3",
    title: "Binary Tree Inorder Traversal",
    difficulty: "Easy",
    leetcode: "https://leetcode.com/problems/binary-tree-inorder-traversal/",
    category: "Trees",
  },
  {
    id: "4",
    title: "Maximum Subarray",
    difficulty: "Medium",
    leetcode: "https://leetcode.com/problems/maximum-subarray/",
    category: "Arrays",
  },
  {
    id: "5",
    title: "Merge Two Sorted Lists",
    difficulty: "Easy",
    leetcode: "https://leetcode.com/problems/merge-two-sorted-lists/",
    category: "Linked List",
  },
  {
    id: "6",
    title: "Valid Parentheses",
    difficulty: "Easy",
    leetcode: "https://leetcode.com/problems/valid-parentheses/",
    category: "Stack",
  },
  {
    id: "7",
    title: "Longest Substring Without Repeating Characters",
    difficulty: "Medium",
    leetcode:
      "https://leetcode.com/problems/longest-substring-without-repeating-characters/",
    category: "Strings",
  },
  {
    id: "8",
    title: "Search in Rotated Sorted Array",
    difficulty: "Medium",
    leetcode: "https://leetcode.com/problems/search-in-rotated-sorted-array/",
    category: "Binary Search",
  },
  {
    id: "9",
    title: "3Sum",
    difficulty: "Medium",
    leetcode: "https://leetcode.com/problems/3sum/",
    category: "Arrays",
  },
  {
    id: "10",
    title: "Container With Most Water",
    difficulty: "Medium",
    leetcode: "https://leetcode.com/problems/container-with-most-water/",
    category: "Two Pointers",
  },
  {
    id: "11",
    title: "Climbing Stairs",
    difficulty: "Easy",
    leetcode: "https://leetcode.com/problems/climbing-stairs/",
    category: "Dynamic Programming",
  },
  {
    id: "12",
    title: "Coin Change",
    difficulty: "Medium",
    leetcode: "https://leetcode.com/problems/coin-change/",
    category: "Dynamic Programming",
  },
  {
    id: "13",
    title: "Word Break",
    difficulty: "Medium",
    leetcode: "https://leetcode.com/problems/word-break/",
    category: "Dynamic Programming",
  },
  {
    id: "14",
    title: "Merge k Sorted Lists",
    difficulty: "Hard",
    leetcode: "https://leetcode.com/problems/merge-k-sorted-lists/",
    category: "Linked List",
  },
  {
    id: "15",
    title: "Minimum Window Substring",
    difficulty: "Hard",
    leetcode: "https://leetcode.com/problems/minimum-window-substring/",
    category: "Sliding Window",
  },
  {
    id: "16",
    title: "Longest Increasing Subsequence",
    difficulty: "Medium",
    leetcode: "https://leetcode.com/problems/longest-increasing-subsequence/",
    category: "Dynamic Programming",
  },
  {
    id: "17",
    title: "Number of Islands",
    difficulty: "Medium",
    leetcode: "https://leetcode.com/problems/number-of-islands/",
    category: "Graphs",
  },
  {
    id: "18",
    title: "Interview – First Bad Version",
    difficulty: "Easy",
    leetcode: "https://leetcode.com/problems/first-bad-version/",
    category: "Binary Search",
  },
  {
    id: "19",
    title: "Maximum Product Subarray",
    difficulty: "Medium",
    leetcode: "https://leetcode.com/problems/maximum-product-subarray/",
    category: "Arrays",
  },
  {
    id: "20",
    title: "Subsets",
    difficulty: "Medium",
    leetcode: "https://leetcode.com/problems/subsets/",
    category: "Backtracking",
  },
  {
    id: "21",
    title: "Generate Parentheses",
    difficulty: "Medium",
    leetcode: "https://leetcode.com/problems/generate-parentheses/",
    category: "Backtracking",
  },
  {
    id: "22",
    title: "Lowest Common Ancestor of a Binary Search Tree",
    difficulty: "Easy",
    leetcode:
      "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/",
    category: "Trees",
  },
  {
    id: "23",
    title: "Validate Binary Search Tree",
    difficulty: "Medium",
    leetcode: "https://leetcode.com/problems/validate-binary-search-tree/",
    category: "Trees",
  },
  {
    id: "24",
    title: "Word Ladder",
    difficulty: "Hard",
    leetcode: "https://leetcode.com/problems/word-ladder/",
    category: "Graphs",
  },
  {
    id: "25",
    title: "Design HashMap",
    difficulty: "Medium",
    leetcode: "https://leetcode.com/problems/design-hashmap/",
    category: "Design",
  },
  {
    id: "26",
    title: "Top K Frequent Elements",
    difficulty: "Medium",
    leetcode: "https://leetcode.com/problems/top-k-frequent-elements/",
    category: "Heap / Priority Queue",
  },
  {
    id: "27",
    title: "Trapping Rain Water",
    difficulty: "Hard",
    leetcode: "https://leetcode.com/problems/trapping-rain-water/",
    category: "Two Pointers",
  },
  {
    id: "28",
    title: "Median of Two Sorted Arrays",
    difficulty: "Hard",
    leetcode: "https://leetcode.com/problems/median-of-two-sorted-arrays/",
    category: "Divide & Conquer",
  },
  {
    id: "29",
    title: "Search a 2D Matrix II",
    difficulty: "Medium",
    leetcode: "https://leetcode.com/problems/search-a-2d-matrix-ii/",
    category: "Binary Search",
  },
  {
    id: "30",
    title: "LRU Cache",
    difficulty: "Hard",
    leetcode: "https://leetcode.com/problems/lru-cache/",
    category: "Design",
  },
  {
    id: "31",
    title: "Number of Connected Components in an Undirected Graph",
    difficulty: "Medium",
    leetcode:
      "https://leetcode.com/problems/number-of-connected-components-in-an-undirected-graph/",
    category: "Graphs",
  },
  {
    id: "32",
    title: "Decode Ways",
    difficulty: "Medium",
    leetcode: "https://leetcode.com/problems/decode-ways/",
    category: "Dynamic Programming",
  },
  {
    id: "33",
    title: "Word Search",
    difficulty: "Medium",
    leetcode: "https://leetcode.com/problems/word-search/",
    category: "Backtracking",
  },
  {
    id: "34",
    title: "House Robber",
    difficulty: "Easy",
    leetcode: "https://leetcode.com/problems/house-robber/",
    category: "Dynamic Programming",
  },
  {
    id: "35",
    title: "Rotate Image",
    difficulty: "Medium",
    leetcode: "https://leetcode.com/problems/rotate-image/",
    category: "Matrix",
  },
  {
    id: "36",
    title: "Spiral Matrix",
    difficulty: "Medium",
    leetcode: "https://leetcode.com/problems/spiral-matrix/",
    category: "Matrix",
  },
  {
    id: "37",
    title: "Kth Largest Element in an Array",
    difficulty: "Medium",
    leetcode: "https://leetcode.com/problems/kth-largest-element-in-an-array/",
    category: "Heap / Priority Queue",
  },
  {
    id: "38",
    title: "Binary Tree Maximum Path Sum",
    difficulty: "Hard",
    leetcode: "https://leetcode.com/problems/binary-tree-maximum-path-sum/",
    category: "Trees",
  },
  {
    id: "39",
    title: "Clone Graph",
    difficulty: "Medium",
    leetcode: "https://leetcode.com/problems/clone-graph/",
    category: "Graphs",
  },
  {
    id: "40",
    title: "Minimum Path Sum",
    difficulty: "Medium",
    leetcode: "https://leetcode.com/problems/minimum-path-sum/",
    category: "Dynamic Programming",
  },
  {
    id: "41",
    title: "Remove Nth Node From End of List",
    difficulty: "Medium",
    leetcode: "https://leetcode.com/problems/remove-nth-node-from-end-of-list/",
    category: "Linked List",
  },
  {
    id: "42",
    title: "Search in a Binary Search Tree",
    difficulty: "Easy",
    leetcode: "https://leetcode.com/problems/search-in-a-binary-search-tree/",
    category: "Trees",
  },
  {
    id: "43",
    title: "Pow(x, n)",
    difficulty: "Medium",
    leetcode: "https://leetcode.com/problems/powx-n/",
    category: "Math / Recursion",
  },
  {
    id: "44",
    title: "Subarray Sum Equals K",
    difficulty: "Medium",
    leetcode: "https://leetcode.com/problems/subarray-sum-equals-k/",
    category: "Arrays",
  },
  {
    id: "45",
    title: "Longest Palindromic Substring",
    difficulty: "Medium",
    leetcode: "https://leetcode.com/problems/longest-palindromic-substring/",
    category: "Strings",
  },
  {
    id: "46",
    title: "Next Permutation",
    difficulty: "Medium",
    leetcode: "https://leetcode.com/problems/next-permutation/",
    category: "Arrays",
  },
  {
    id: "47",
    title: "Jump Game",
    difficulty: "Medium",
    leetcode: "https://leetcode.com/problems/jump-game/",
    category: "Dynamic Programming / Greedy",
  },
  {
    id: "48",
    title: "Find First and Last Position of Element in Sorted Array",
    difficulty: "Medium",
    leetcode:
      "https://leetcode.com/problems/find-first-and-last-position-of-element-in-sorted-array/",
    category: "Binary Search",
  },
  {
    id: "49",
    title: "Word Ladder II",
    difficulty: "Hard",
    leetcode: "https://leetcode.com/problems/word-ladder-ii/",
    category: "Graphs / BFS",
  },
  {
    id: "50",
    title: "Evaluate Reverse Polish Notation",
    difficulty: "Medium",
    leetcode: "https://leetcode.com/problems/evaluate-reverse-polish-notation/",
    category: "Stack",
  },
  {
    id: "51",
    title: "Contains Duplicate",
    difficulty: "Easy",
    leetcode: "https://leetcode.com/problems/contains-duplicate/",
    category: "Arrays",
  },
  {
    id: "52",
    title: "Product of Array Except Self",
    difficulty: "Medium",
    leetcode: "https://leetcode.com/problems/product-of-array-except-self/",
    category: "Arrays",
  },
  {
    id: "53",
    title: "Missing Number",
    difficulty: "Easy",
    leetcode: "https://leetcode.com/problems/missing-number/",
    category: "Arrays",
  },
  {
    id: "54",
    title: "Find Minimum in Rotated Sorted Array",
    difficulty: "Medium",
    leetcode:
      "https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/",
    category: "Binary Search",
  },
  {
    id: "55",
    title: "Search Insert Position",
    difficulty: "Easy",
    leetcode: "https://leetcode.com/problems/search-insert-position/",
    category: "Binary Search",
  },
  {
    id: "56",
    title: "Sort Colors",
    difficulty: "Medium",
    leetcode: "https://leetcode.com/problems/sort-colors/",
    category: "Two Pointers",
  },
  {
    id: "57",
    title: "Majority Element",
    difficulty: "Easy",
    leetcode: "https://leetcode.com/problems/majority-element/",
    category: "Arrays",
  },
  {
    id: "58",
    title: "Spiral Matrix II",
    difficulty: "Medium",
    leetcode: "https://leetcode.com/problems/spiral-matrix-ii/",
    category: "Matrix",
  },
  {
    id: "59",
    title: "Jump Game II",
    difficulty: "Medium",
    leetcode: "https://leetcode.com/problems/jump-game-ii/",
    category: "Greedy / DP",
  },
  {
    id: "60",
    title: "Word Search II",
    difficulty: "Hard",
    leetcode: "https://leetcode.com/problems/word-search-ii/",
    category: "Backtracking / Trie",
  },
  {
    id: "61",
    title: "Minimum Size Subarray Sum",
    difficulty: "Medium",
    leetcode: "https://leetcode.com/problems/minimum-size-subarray-sum/",
    category: "Sliding Window",
  },
  {
    id: "62",
    title: "Longest Consecutive Sequence",
    difficulty: "Hard",
    leetcode: "https://leetcode.com/problems/longest-consecutive-sequence/",
    category: "Hash Table / Union Find",
  },
  {
    id: "63",
    title: "Binary Tree level Order Traversal",
    difficulty: "Medium",
    leetcode:
      "https://leetcode.com/problems/binary-tree-level-order-traversal/",
    category: "Trees",
  },
  {
    id: "64",
    title: "Symmetric Tree",
    difficulty: "Easy",
    leetcode: "https://leetcode.com/problems/symmetric-tree/",
    category: "Trees",
  },
  {
    id: "65",
    title: "Lowest Common Ancestor of a Binary Tree",
    difficulty: "Medium",
    leetcode:
      "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/",
    category: "Trees",
  },
  {
    id: "66",
    title: "Serialize and Deserialize Binary Tree",
    difficulty: "Hard",
    leetcode:
      "https://leetcode.com/problems/serialize-and-deserialize-binary-tree/",
    category: "Trees / Design",
  },
  {
    id: "67",
    title: "Course Schedule",
    difficulty: "Medium",
    leetcode: "https://leetcode.com/problems/course-schedule/",
    category: "Graphs",
  },
  {
    id: "68",
    title: "Alien Dictionary",
    difficulty: "Hard",
    leetcode: "https://leetcode.com/problems/alien-dictionary/",
    category: "Graphs / Topological Sort",
  },
  {
    id: "69",
    title: "Number of Islands II",
    difficulty: "Hard",
    leetcode: "https://leetcode.com/problems/number-of-islands-ii/",
    category: "Graphs / Union Find",
  },
  {
    id: "70",
    title: "Top K Frequent Elements",
    difficulty: "Medium",
    leetcode: "https://leetcode.com/problems/top-k-frequent-elements/",
    category: "Heap / Priority Queue",
  },
  {
    id: "71",
    title: "Merge Intervals",
    difficulty: "Medium",
    leetcode: "https://leetcode.com/problems/merge-intervals/",
    category: "Intervals",
  },
  {
    id: "72",
    title: "Insert Interval",
    difficulty: "Hard",
    leetcode: "https://leetcode.com/problems/insert-interval/",
    category: "Intervals",
  },
  {
    id: "73",
    title: "K Closest Points to Origin",
    difficulty: "Medium",
    leetcode: "https://leetcode.com/problems/k-closest-points-to-origin/",
    category: "Heap / Math",
  },
  {
    id: "74",
    title: "Find Median from Data Stream",
    difficulty: "Hard",
    leetcode: "https://leetcode.com/problems/find-median-from-data-stream/",
    category: "Heap / Design",
  },
  {
    id: "75",
    title: "Implement Trie (Prefix Tree)",
    difficulty: "Medium",
    leetcode: "https://leetcode.com/problems/implement-trie-prefix-tree/",
    category: "Trie",
  },
  {
    id: "76",
    title: "Word Pattern",
    difficulty: "Easy",
    leetcode: "https://leetcode.com/problems/word-pattern/",
    category: "Strings / Hash Table",
  },
  {
    id: "77",
    title: "Longest Valid Parentheses",
    difficulty: "Hard",
    leetcode: "https://leetcode.com/problems/longest-valid-parentheses/",
    category: "Stack / DP",
  },
  {
    id: "78",
    title: "Largest Rectangle in Histogram",
    difficulty: "Hard",
    leetcode: "https://leetcode.com/problems/largest-rectangle-in-histogram/",
    category: "Stack / Array",
  },
  {
    id: "79",
    title: "Min Stack",
    difficulty: "Easy",
    leetcode: "https://leetcode.com/problems/min-stack/",
    category: "Stack / Design",
  },
  {
    id: "80",
    title: "Sliding Window Maximum",
    difficulty: "Hard",
    leetcode: "https://leetcode.com/problems/sliding-window-maximum/",
    category: "Deque / Sliding Window",
  },
  {
    id: "81",
    title: "Merge Sorted Array",
    difficulty: "Easy",
    leetcode: "https://leetcode.com/problems/merge-sorted-array/",
    category: "Arrays",
  },
  {
    id: "82",
    title: "Combinations",
    difficulty: "Medium",
    leetcode: "https://leetcode.com/problems/combinations/",
    category: "Backtracking",
  },
  {
    id: "83",
    title: "Permutation Sequence",
    difficulty: "Medium",
    leetcode: "https://leetcode.com/problems/permutation-sequence/",
    category: "Math / Backtracking",
  },
  {
    id: "84",
    title: "Decode String",
    difficulty: "Medium",
    leetcode: "https://leetcode.com/problems/decode-string/",
    category: "Stack / Recursion",
  },
  {
    id: "85",
    title: "Basic Calculator II",
    difficulty: "Medium",
    leetcode: "https://leetcode.com/problems/basic-calculator-ii/",
    category: "Stack / Math",
  },
  {
    id: "86",
    title: "Evaluate Division",
    difficulty: "Medium",
    leetcode: "https://leetcode.com/problems/evaluate-division/",
    category: "Graph / DFS",
  },
  {
    id: "87",
    title: "Word Ladder I",
    difficulty: "Medium",
    leetcode: "https://leetcode.com/problems/word-ladder/",
    category: "Graphs / BFS",
  },
  {
    id: "88",
    title: "Minimum Window Subsequence",
    difficulty: "Hard",
    leetcode: "https://leetcode.com/problems/minimum-window-subsequence/",
    category: "Strings / Two Pointers",
  },
  {
    id: "89",
    title: "Binary Search Tree Iterator",
    difficulty: "Medium",
    leetcode: "https://leetcode.com/problems/binary-search-tree-iterator/",
    category: "Trees / Design",
  },
  {
    id: "90",
    title: "Flatten Nested List Iterator",
    difficulty: "Medium",
    leetcode: "https://leetcode.com/problems/flatten-nested-list-iterator/",
    category: "Design / Stack",
  },
  {
    id: "91",
    title: "Serialize and Deserialize BST",
    difficulty: "Hard",
    leetcode: "https://leetcode.com/problems/serialize-and-deserialize-bst/",
    category: "Trees / Design",
  },
  {
    id: "92",
    title: "Maximum Depth of N-ary Tree",
    difficulty: "Easy",
    leetcode: "https://leetcode.com/problems/maximum-depth-of-n-ary-tree/",
    category: "Trees",
  },
  {
    id: "93",
    title: "Sum of Subarray Minimums",
    difficulty: "Hard",
    leetcode: "https://leetcode.com/problems/sum-of-subarray-minimums/",
    category: "Stack / DP",
  },
  {
    id: "94",
    title: "Number of Digit One",
    difficulty: "Hard",
    leetcode: "https://leetcode.com/problems/number-of-digit-one/",
    category: "Math / Counting",
  },
  {
    id: "95",
    title: "The Skyline Problem",
    difficulty: "Hard",
    leetcode: "https://leetcode.com/problems/the-skyline-problem/",
    category: "Divide & Conquer / Heap",
  },
  {
    id: "96",
    title: "Binary Indexed Tree / Fenwick Tree Implementation",
    difficulty: "Hard",
    leetcode: "https://leetcode.com/problems/range-sum-query-mutable/",
    category: "Data Structure",
  },
  {
    id: "97",
    title: "Maximum XOR of Two Numbers in an Array",
    difficulty: "Hard",
    leetcode:
      "https://leetcode.com/problems/maximum-xor-of-two-numbers-in-an-array/",
    category: "Bit Manipulation / Trie",
  },
  {
    id: "98",
    title: "Concatenated Words",
    difficulty: "Hard",
    leetcode: "https://leetcode.com/problems/concatenated-words/",
    category: "Tries / DP",
  },
  {
    id: "99",
    title: "Expression Add Operators",
    difficulty: "Hard",
    leetcode: "https://leetcode.com/problems/expression-add-operators/",
    category: "Backtracking / Math",
  },
  {
    id: "100",
    title: "Longest Increasing Path in a Matrix",
    difficulty: "Hard",
    leetcode:
      "https://leetcode.com/problems/longest-increasing-path-in-a-matrix/",
    category: "Graph / DP",
  },
];

export const facts: FactCard[] = [
  {
    id: "1",
    title: "JavaScript Fun Fact",
    description:
      "JavaScript was created in just 10 days by Brendan Eich in 1995.",
    language: "JavaScript",
  },
  {
    id: "2",
    title: "Python Philosophy",
    description:
      'Python follows the Zen of Python, which includes "Beautiful is better than ugly."',
    language: "Python",
  },
  {
    id: "3",
    title: "TypeScript Growth",
    description:
      "TypeScript usage grew by 78% in 2022 according to Stack Overflow survey.",
    language: "TypeScript",
  },
  {
    id: "4",
    title: "Rust Memory Safety",
    description:
      "Rust guarantees memory safety without garbage collection using its ownership system.",
    language: "Rust",
  },
  {
    id: "5",
    title: "Go Concurrency",
    description:
      "Go was designed with concurrency in mind, featuring goroutines and channels.",
    language: "Go",
  },
  {
    id: "6",
    title: "C Language Origin",
    description:
      "The C programming language was developed at Bell Labs by Dennis Ritchie in the early 1970s.",
    language: "C",
  },
  {
    id: "7",
    title: "C++ Name Story",
    description:
      "C++ gets its name from the increment operator (++), symbolizing an evolution of C.",
    language: "C++",
  },
  {
    id: "8",
    title: "Java Motto",
    description:
      "Java’s philosophy is 'Write Once, Run Anywhere' thanks to the Java Virtual Machine (JVM).",
    language: "Java",
  },
  {
    id: "9",
    title: "React Invention",
    description:
      "React was created by a Facebook engineer, Jordan Walke, in 2013.",
    language: "React",
  },
  {
    id: "10",
    title: "Node.js Power",
    description:
      "Node.js uses the V8 engine from Google Chrome to run JavaScript on servers.",
    language: "Node.js",
  },
  {
    id: "11",
    title: "HTML Roots",
    description:
      "HTML was first created by Tim Berners-Lee in 1991 to share scientific documents online.",
    language: "HTML",
  },
  {
    id: "12",
    title: "CSS Magic",
    description:
      "CSS stands for Cascading Style Sheets and was first proposed in 1994 by Håkon Wium Lie.",
    language: "CSS",
  },
  {
    id: "13",
    title: "PHP Origin",
    description:
      "PHP originally stood for 'Personal Home Page' before becoming 'PHP: Hypertext Preprocessor'.",
    language: "PHP",
  },
  {
    id: "14",
    title: "Kotlin Boost",
    description:
      "Google announced Kotlin as an official Android language in 2017.",
    language: "Kotlin",
  },
  {
    id: "15",
    title: "Swift Simplicity",
    description:
      "Swift was designed to be safer and faster than Objective-C for Apple development.",
    language: "Swift",
  },
  {
    id: "16",
    title: "SQL Power",
    description:
      "SQL has been the standard language for relational databases since 1986.",
    language: "SQL",
  },
  {
    id: "17",
    title: "React Native Power",
    description:
      "React Native allows building mobile apps using JavaScript and React concepts.",
    language: "React Native",
  },
  {
    id: "18",
    title: "Tailwind CSS Utility",
    description:
      "Tailwind CSS promotes a utility-first approach, allowing faster UI building.",
    language: "Tailwind CSS",
  },
  {
    id: "19",
    title: "Docker Containers",
    description:
      "Docker revolutionized deployment by introducing lightweight containers.",
    language: "Docker",
  },
  {
    id: "20",
    title: "Git Invention",
    description:
      "Git was created by Linus Torvalds in 2005 to manage Linux kernel development.",
    language: "Git",
  },
  {
    id: "21",
    title: "GraphQL Evolution",
    description:
      "GraphQL, created by Facebook, allows clients to request exactly the data they need.",
    language: "GraphQL",
  },
  {
    id: "22",
    title: "Firebase Realtime",
    description:
      "Firebase offers realtime databases and easy integration for mobile and web apps.",
    language: "Firebase",
  },
  {
    id: "23",
    title: "AI Coding",
    description:
      "Machine learning is being integrated into code editors for smarter assistance.",
    language: "AI",
  },
  {
    id: "24",
    title: "VS Code Popularity",
    description:
      "VS Code is one of the most loved developer editors, made by Microsoft.",
    language: "Tools",
  },
  {
    id: "25",
    title: "Open Source Power",
    description:
      "Most programming tools today are open-source and community-driven.",
    language: "Community",
  },
];

export const installationGuides = [
  {
    id: "1",
    title: "Node.js & npm",
    description:
      "Install Node.js and npm package manager for JavaScript development",
    category: "Runtime",
    difficulty: "Beginner",
    steps: [
      {
        title: "Download Node.js",
        description:
          "Visit the official Node.js website and download the LTS version",
        command: "# Download from https://nodejs.org/",
      },
      {
        title: "Verify Installation",
        description: "Check if Node.js and npm are installed correctly",
        command: "node --version\nnpm --version",
      },
      {
        title: "Update npm (Optional)",
        description: "Update npm to the latest version",
        command: "npm install -g npm@latest",
      },
    ],
    verified: true,
  },
  {
    id: "2",
    title: "Python",
    description: "Install Python and pip package manager",
    category: "Language",
    difficulty: "Beginner",
    steps: [
      {
        title: "Download Python",
        description: "Download Python from the official website",
        command: "# Download from https://python.org/downloads/",
      },
      {
        title: "Verify Installation",
        description: "Check Python and pip installation",
        command: "python --version\npip --version",
      },
      {
        title: "Set up Virtual Environment",
        description: "Create and activate a virtual environment",
        command:
          "python -m venv myenv\nsource myenv/bin/activate  # Linux/Mac\nmyenv\\Scripts\\activate  # Windows",
      },
    ],
    verified: true,
  },
  {
    id: "3",
    title: "Git",
    description: "Install Git version control system",
    category: "Tools",
    difficulty: "Beginner",
    steps: [
      {
        title: "Download Git",
        description: "Download Git from the official website",
        command: "# Download from https://git-scm.com/downloads",
      },
      {
        title: "Verify Installation",
        description: "Check Git installation",
        command: "git --version",
      },
      {
        title: "Configure Git",
        description: "Set up your username and email",
        command:
          'git config --global user.name "Your Name"\ngit config --global user.email "your.email@example.com"',
      },
    ],
    verified: true,
  },
  {
    id: "4",
    title: "Docker",
    description: "Install Docker for containerization",
    category: "Tools",
    difficulty: "Intermediate",
    steps: [
      {
        title: "Download Docker",
        description: "Download Docker Desktop from the official website",
        command: "# Download from https://docker.com/get-started",
      },
      {
        title: "Verify Installation",
        description: "Check Docker installation",
        command: "docker --version\ndocker-compose --version",
      },
      {
        title: "Run Test Container",
        description: "Run a test container to verify installation",
        command: "docker run hello-world",
      },
    ],
    verified: true,
  },
  {
    id: "5",
    title: "React",
    description: "Set up React development environment",
    category: "Framework",
    difficulty: "Beginner",
    steps: [
      {
        title: "Create React App",
        description: "Use Create React App to set up a new project",
        command: "npx create-react-app my-app",
      },
      {
        title: "Navigate to Project",
        description: "Change to the project directory",
        command: "cd my-app",
      },
      {
        title: "Start Development Server",
        description: "Start the development server",
        command: "npm start",
      },
    ],
    verified: true,
  },
  {
    id: "6",
    title: "Next.js",
    description: "Install Next.js framework",
    category: "Framework",
    difficulty: "Beginner",
    steps: [
      {
        title: "Create Next.js App",
        description: "Use create-next-app to set up a new project",
        command: "npx create-next-app@latest my-app",
      },
      {
        title: "Navigate to Project",
        description: "Change to the project directory",
        command: "cd my-app",
      },
      {
        title: "Start Development Server",
        description: "Start the development server",
        command: "npm run dev",
      },
    ],
    verified: true,
  },
  {
    id: "7",
    title: "MongoDB",
    description: "Install MongoDB for local database setup",
    category: "Database",
    difficulty: "Intermediate",
    steps: [
      {
        title: "Download MongoDB",
        description: "Download MongoDB Community Server",
        command: "# https://www.mongodb.com/try/download/community",
      },
      {
        title: "Start MongoDB Service",
        description: "Start the MongoDB daemon process",
        command: "sudo service mongod start",
      },
      {
        title: "Verify Connection",
        description: "Use Mongo shell to test connection",
        command: "mongo --version",
      },
    ],
    verified: true,
  },
  {
    id: "8",
    title: "PostgreSQL",
    description: "Install PostgreSQL relational database",
    category: "Database",
    difficulty: "Intermediate",
    steps: [
      {
        title: "Install PostgreSQL",
        description: "Install using package manager or installer",
        command: "sudo apt install postgresql postgresql-contrib",
      },
      {
        title: "Start Service",
        description: "Start PostgreSQL service",
        command: "sudo service postgresql start",
      },
      {
        title: "Open SQL Shell",
        description: "Access PostgreSQL shell",
        command: "psql -U postgres",
      },
    ],
    verified: true,
  },
  {
    id: "9",
    title: "VS Code",
    description: "Install Visual Studio Code editor",
    category: "IDE",
    difficulty: "Beginner",
    steps: [
      {
        title: "Download VS Code",
        description: "Download from the official website",
        command: "# https://code.visualstudio.com/download",
      },
      {
        title: "Install Extensions",
        description: "Install popular extensions like Prettier, ESLint",
        command: "Use Ctrl+Shift+X in VS Code to open Extensions panel",
      },
    ],
    verified: true,
  },
  {
    id: "10",
    title: "Firebase CLI",
    description: "Install Firebase Command Line Interface",
    category: "Tools",
    difficulty: "Intermediate",
    steps: [
      {
        title: "Install Firebase Tools",
        description: "Use npm to install Firebase CLI globally",
        command: "npm install -g firebase-tools",
      },
      {
        title: "Login to Firebase",
        description: "Authenticate your Firebase account",
        command: "firebase login",
      },
      {
        title: "Initialize Project",
        description: "Set up Firebase in your project",
        command: "firebase init",
      },
    ],
    verified: true,
  },
  {
    id: "11",
    title: "TypeScript",
    description: "Install TypeScript compiler globally",
    category: "Language",
    difficulty: "Beginner",
    steps: [
      {
        title: "Install TypeScript",
        description: "Use npm to install globally",
        command: "npm install -g typescript",
      },
      {
        title: "Verify Installation",
        description: "Check TypeScript version",
        command: "tsc --version",
      },
      {
        title: "Initialize tsconfig.json",
        description: "Create a TypeScript configuration file",
        command: "tsc --init",
      },
    ],
    verified: true,
  },
  {
    id: "12",
    title: "Vite",
    description: "Install Vite build tool for fast frontend setup",
    category: "Build Tool",
    difficulty: "Beginner",
    steps: [
      {
        title: "Create Vite App",
        description: "Initialize a new project with Vite",
        command: "npm create vite@latest my-app",
      },
      {
        title: "Install Dependencies",
        description: "Install project dependencies",
        command: "npm install",
      },
      {
        title: "Run Development Server",
        description: "Start the local dev server",
        command: "npm run dev",
      },
    ],
    verified: true,
  },
  {
    id: "13",
    title: "Tailwind CSS",
    description: "Set up Tailwind CSS in your project",
    category: "CSS Framework",
    difficulty: "Beginner",
    steps: [
      {
        title: "Install Tailwind via npm",
        description: "Add Tailwind to your project",
        command: "npm install -D tailwindcss postcss autoprefixer",
      },
      {
        title: "Initialize Tailwind Config",
        description: "Generate configuration files",
        command: "npx tailwindcss init -p",
      },
      {
        title: "Add Tailwind Directives",
        description: "Add Tailwind to your CSS file",
        command: "@tailwind base;\n@tailwind components;\n@tailwind utilities;",
      },
    ],
    verified: true,
  },
  {
    id: "14",
    title: "Redux Toolkit",
    description: "Set up Redux Toolkit for state management",
    category: "Library",
    difficulty: "Intermediate",
    steps: [
      {
        title: "Install Redux Toolkit",
        description: "Add Redux Toolkit and React-Redux",
        command: "npm install @reduxjs/toolkit react-redux",
      },
      {
        title: "Create a Store",
        description: "Configure the Redux store",
        command: "configureStore({ reducer: { counter: counterReducer } })",
      },
    ],
    verified: true,
  },
  {
    id: "15",
    title: "Express.js",
    description: "Set up Express for backend development",
    category: "Backend",
    difficulty: "Intermediate",
    steps: [
      {
        title: "Install Express",
        description: "Use npm to install Express",
        command: "npm install express",
      },
      {
        title: "Create Server",
        description: "Create a simple Express server",
        command: `const express = require('express');
const app = express();
app.listen(3000, () => console.log('Server running'));`,
      },
    ],
    verified: true,
  },
  {
    id: "16",
    title: "MySQL",
    description: "Install MySQL Database Server",
    category: "Database",
    difficulty: "Intermediate",
    steps: [
      {
        title: "Install MySQL",
        description: "Download and install from official source",
        command: "# https://dev.mysql.com/downloads/",
      },
      {
        title: "Verify Installation",
        description: "Check MySQL version",
        command: "mysql --version",
      },
    ],
    verified: true,
  },
  {
    id: "17",
    title: "Postman",
    description: "Install Postman API testing tool",
    category: "Tools",
    difficulty: "Beginner",
    steps: [
      {
        title: "Download Postman",
        description: "Download from the official website",
        command: "# https://www.postman.com/downloads/",
      },
    ],
    verified: true,
  },
  {
    id: "18",
    title: "AWS CLI",
    description: "Install AWS Command Line Interface",
    category: "Cloud",
    difficulty: "Intermediate",
    steps: [
      {
        title: "Install AWS CLI",
        description: "Use pip to install AWS CLI",
        command: "pip install awscli --upgrade --user",
      },
      {
        title: "Configure AWS",
        description: "Set up credentials",
        command: "aws configure",
      },
    ],
    verified: true,
  },
  {
    id: "19",
    title: "Netlify CLI",
    description: "Deploy your site using Netlify CLI",
    category: "Deployment",
    difficulty: "Beginner",
    steps: [
      {
        title: "Install Netlify CLI",
        description: "Install globally using npm",
        command: "npm install -g netlify-cli",
      },
      {
        title: "Login and Deploy",
        description: "Login and deploy project",
        command: "netlify login\nnetlify deploy",
      },
    ],
    verified: true,
  },
  {
    id: "20",
    title: "pnpm",
    description: "Install pnpm — fast, disk-efficient package manager",
    category: "Tools",
    difficulty: "Beginner",
    steps: [
      {
        title: "Install pnpm",
        description: "Install using npm",
        command: "npm install -g pnpm",
      },
      {
        title: "Verify Installation",
        description: "Check pnpm version",
        command: "pnpm -v",
      },
    ],
    verified: true,
  },
  {
    id: "21",
    title: "Flutter",
    description: "Install Flutter SDK for cross-platform app development",
    category: "Framework",
    difficulty: "Intermediate",
    steps: [
      {
        title: "Download Flutter SDK",
        description: "Download Flutter from the official site",
        command: "# https://flutter.dev/docs/get-started/install",
      },
      {
        title: "Add Flutter to PATH",
        description: "Add Flutter bin directory to your system PATH",
        command: 'export PATH="$PATH:`pwd`/flutter/bin"',
      },
      {
        title: "Verify Installation",
        description: "Run Flutter doctor to verify setup",
        command: "flutter doctor",
      },
    ],
    verified: true,
  },
  {
    id: "22",
    title: "Android Studio",
    description: "Install Android Studio for Android app development",
    category: "IDE",
    difficulty: "Intermediate",
    steps: [
      {
        title: "Download Android Studio",
        description: "Download and install from official website",
        command: "# https://developer.android.com/studio",
      },
      {
        title: "Install SDK Tools",
        description: "Use SDK Manager to install Android SDK",
        command: "Tools → SDK Manager → Android SDK",
      },
      {
        title: "Verify Setup",
        description: "Check emulator or device connection",
        command: "adb devices",
      },
    ],
    verified: true,
  },
  {
    id: "23",
    title: "Redis",
    description: "Install Redis in-memory data store",
    category: "Database",
    difficulty: "Intermediate",
    steps: [
      {
        title: "Install Redis",
        description: "Install using package manager",
        command: "sudo apt install redis-server",
      },
      {
        title: "Start Redis Server",
        description: "Start the Redis service",
        command: "sudo service redis-server start",
      },
      {
        title: "Verify Installation",
        description: "Ping Redis to test connection",
        command: "redis-cli ping",
      },
    ],
    verified: true,
  },
  {
    id: "24",
    title: "GraphQL",
    description: "Set up GraphQL server using Apollo",
    category: "Backend",
    difficulty: "Intermediate",
    steps: [
      {
        title: "Install Apollo Server",
        description: "Install Apollo and GraphQL dependencies",
        command: "npm install @apollo/server graphql",
      },
      {
        title: "Create Basic Server",
        description: "Create schema and resolver setup",
        command: `import { ApolloServer } from "@apollo/server";`,
      },
    ],
    verified: true,
  },
  {
    id: "25",
    title: "Prisma ORM",
    description: "Install and configure Prisma ORM",
    category: "Database",
    difficulty: "Intermediate",
    steps: [
      {
        title: "Install Prisma",
        description: "Install Prisma CLI",
        command: "npm install prisma --save-dev",
      },
      {
        title: "Initialize Prisma",
        description: "Initialize Prisma schema",
        command: "npx prisma init",
      },
    ],
    verified: true,
  },
  {
    id: "26",
    title: "Supabase CLI",
    description: "Install Supabase CLI for local backend setup",
    category: "Cloud",
    difficulty: "Intermediate",
    steps: [
      {
        title: "Install Supabase CLI",
        description: "Use npm to install",
        command: "npm install -g supabase",
      },
      {
        title: "Login & Init Project",
        description: "Authenticate and set up new project",
        command: "supabase login\nsupabase init",
      },
    ],
    verified: true,
  },
  {
    id: "27",
    title: "Bun",
    description: "Install Bun JavaScript runtime and package manager",
    category: "Runtime",
    difficulty: "Beginner",
    steps: [
      {
        title: "Install Bun",
        description: "Install using shell command",
        command: "curl -fsSL https://bun.sh/install | bash",
      },
      {
        title: "Verify Installation",
        description: "Check Bun version",
        command: "bun -v",
      },
    ],
    verified: true,
  },
  {
    id: "28",
    title: "Rust",
    description: "Install Rust programming language",
    category: "Language",
    difficulty: "Intermediate",
    steps: [
      {
        title: "Install via rustup",
        description: "Use official installer",
        command: "curl https://sh.rustup.rs -sSf | sh",
      },
      {
        title: "Verify Installation",
        description: "Check Rust version",
        command: "rustc --version",
      },
    ],
    verified: true,
  },
  {
    id: "29",
    title: "Go (Golang)",
    description: "Install Go programming language",
    category: "Language",
    difficulty: "Intermediate",
    steps: [
      {
        title: "Download Go",
        description: "Install from official website",
        command: "# https://go.dev/dl/",
      },
      {
        title: "Verify Installation",
        description: "Check Go version",
        command: "go version",
      },
    ],
    verified: true,
  },
  {
    id: "30",
    title: "Java (JDK)",
    description: "Install Java Development Kit (JDK)",
    category: "Language",
    difficulty: "Beginner",
    steps: [
      {
        title: "Install OpenJDK",
        description: "Install JDK using package manager",
        command: "sudo apt install openjdk-17-jdk",
      },
      {
        title: "Verify Installation",
        description: "Check Java version",
        command: "java -version",
      },
    ],
    verified: true,
  },
  {
    id: "31",
    title: "Visual Studio",
    description: "Install Visual Studio IDE for .NET & C++",
    category: "IDE",
    difficulty: "Intermediate",
    steps: [
      {
        title: "Download Visual Studio",
        description: "Install from Microsoft official site",
        command: "# https://visualstudio.microsoft.com/",
      },
    ],
    verified: true,
  },
  {
    id: "32",
    title: "Kubernetes (kubectl)",
    description: "Install kubectl for Kubernetes management",
    category: "DevOps",
    difficulty: "Advanced",
    steps: [
      {
        title: "Install kubectl",
        description: "Download using curl command",
        command:
          "curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl",
      },
      {
        title: "Verify Installation",
        description: "Check kubectl version",
        command: "kubectl version --client",
      },
    ],
    verified: true,
  },
  {
    id: "33",
    title: "Yarn",
    description: "Install Yarn package manager",
    category: "Tools",
    difficulty: "Beginner",
    steps: [
      {
        title: "Install Yarn",
        description: "Use npm to install globally",
        command: "npm install -g yarn",
      },
      {
        title: "Verify Installation",
        description: "Check Yarn version",
        command: "yarn -v",
      },
    ],
    verified: true,
  },
  {
    id: "34",
    title: "Jest",
    description: "Set up Jest for unit testing in JavaScript",
    category: "Testing",
    difficulty: "Intermediate",
    steps: [
      {
        title: "Install Jest",
        description: "Install as a dev dependency",
        command: "npm install --save-dev jest",
      },
      {
        title: "Add Test Script",
        description: "Add to package.json",
        command: `"scripts": { "test": "jest" }`,
      },
    ],
    verified: true,
  },
  {
    id: "35",
    title: "Cypress",
    description: "Install Cypress for end-to-end testing",
    category: "Testing",
    difficulty: "Intermediate",
    steps: [
      {
        title: "Install Cypress",
        description: "Add Cypress as dev dependency",
        command: "npm install cypress --save-dev",
      },
      {
        title: "Run Cypress",
        description: "Open Cypress UI",
        command: "npx cypress open",
      },
    ],
    verified: true,
  },
  {
    id: "36",
    title: "ESLint",
    description: "Set up ESLint for linting JavaScript/TypeScript code",
    category: "Tools",
    difficulty: "Beginner",
    steps: [
      {
        title: "Install ESLint",
        description: "Install ESLint as a dev dependency",
        command: "npm install eslint --save-dev",
      },
      {
        title: "Initialize Config",
        description: "Generate ESLint config file",
        command: "npx eslint --init",
      },
    ],
    verified: true,
  },
  {
    id: "37",
    title: "Prettier",
    description: "Install Prettier for code formatting",
    category: "Tools",
    difficulty: "Beginner",
    steps: [
      {
        title: "Install Prettier",
        description: "Install as dev dependency",
        command: "npm install --save-dev prettier",
      },
      {
        title: "Add Format Script",
        description: "Add to package.json",
        command: `"scripts": { "format": "prettier --write ." }`,
      },
    ],
    verified: true,
  },
  {
    id: "38",
    title: "Nodemon",
    description: "Install Nodemon for auto server restarts",
    category: "Tools",
    difficulty: "Beginner",
    steps: [
      {
        title: "Install Nodemon",
        description: "Install globally or locally",
        command: "npm install -g nodemon",
      },
      {
        title: "Run Server with Nodemon",
        description: "Use Nodemon for live server reload",
        command: "nodemon server.js",
      },
    ],
    verified: true,
  },
  {
    id: "39",
    title: "Zustand",
    description: "Set up Zustand for simple React state management",
    category: "Library",
    difficulty: "Beginner",
    steps: [
      {
        title: "Install Zustand",
        description: "Install via npm",
        command: "npm install zustand",
      },
    ],
    verified: true,
  },
  {
    id: "40",
    title: "Expo CLI",
    description: "Install Expo CLI for React Native",
    category: "Framework",
    difficulty: "Intermediate",
    steps: [
      {
        title: "Install Expo CLI",
        description: "Install globally",
        command: "npm install -g expo-cli",
      },
      {
        title: "Create Project",
        description: "Start new React Native app",
        command: "expo init my-app",
      },
    ],
    verified: true,
  },
  {
    id: "41",
    title: "React Native CLI",
    description: "Install React Native CLI for native development",
    category: "Framework",
    difficulty: "Intermediate",
    steps: [
      {
        title: "Install CLI",
        description: "Install globally",
        command: "npm install -g react-native-cli",
      },
      {
        title: "Create App",
        description: "Initialize new project",
        command: "npx react-native init MyApp",
      },
    ],
    verified: true,
  },
  {
    id: "42",
    title: "Vercel CLI",
    description: "Deploy projects easily using Vercel CLI",
    category: "Deployment",
    difficulty: "Beginner",
    steps: [
      {
        title: "Install Vercel CLI",
        description: "Install globally via npm",
        command: "npm install -g vercel",
      },
      {
        title: "Login & Deploy",
        description: "Deploy your project to Vercel",
        command: "vercel login\nvercel deploy",
      },
    ],
    verified: true,
  },
  {
    id: "43",
    title: "Deno",
    description: "Install Deno runtime for modern JavaScript & TypeScript",
    category: "Runtime",
    difficulty: "Intermediate",
    steps: [
      {
        title: "Install Deno",
        description: "Use shell command to install",
        command: "curl -fsSL https://deno.land/install.sh | sh",
      },
      {
        title: "Verify Installation",
        description: "Check version",
        command: "deno --version",
      },
    ],
    verified: true,
  },
  {
    id: "44",
    title: "ngrok",
    description: "Install ngrok for local server tunneling",
    category: "Tools",
    difficulty: "Beginner",
    steps: [
      {
        title: "Download ngrok",
        description: "Download from official website",
        command: "# https://ngrok.com/download",
      },
      {
        title: "Expose Port",
        description: "Forward local port",
        command: "ngrok http 3000",
      },
    ],
    verified: true,
  },
  {
    id: "45",
    title: "Heroku CLI",
    description: "Install Heroku CLI for app deployment",
    category: "Deployment",
    difficulty: "Beginner",
    steps: [
      {
        title: "Install CLI",
        description: "Install via npm or package manager",
        command: "npm install -g heroku",
      },
      {
        title: "Login and Deploy",
        description: "Login and push app",
        command: "heroku login\ngit push heroku main",
      },
    ],
    verified: true,
  },
  {
    id: "46",
    title: "Azure CLI",
    description: "Install Azure CLI for cloud management",
    category: "Cloud",
    difficulty: "Advanced",
    steps: [
      {
        title: "Install CLI",
        description: "Install using command line",
        command: "curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash",
      },
      {
        title: "Login",
        description: "Authenticate your Azure account",
        command: "az login",
      },
    ],
    verified: true,
  },
  {
    id: "47",
    title: "Husky",
    description: "Set up Husky for Git hooks",
    category: "Tools",
    difficulty: "Intermediate",
    steps: [
      {
        title: "Install Husky",
        description: "Add as dev dependency",
        command: "npm install husky --save-dev",
      },
      {
        title: "Enable Hooks",
        description: "Initialize Git hooks",
        command: "npx husky install",
      },
    ],
    verified: true,
  },
  {
    id: "48",
    title: "Jupyter Notebook",
    description: "Install Jupyter Notebook for Python development",
    category: "IDE",
    difficulty: "Beginner",
    steps: [
      {
        title: "Install Jupyter",
        description: "Use pip to install",
        command: "pip install notebook",
      },
      {
        title: "Start Notebook",
        description: "Run Jupyter locally",
        command: "jupyter notebook",
      },
    ],
    verified: true,
  },
  {
    id: "49",
    title: "nvm",
    description: "Install Node Version Manager to switch Node versions",
    category: "Tools",
    difficulty: "Intermediate",
    steps: [
      {
        title: "Install nvm",
        description: "Run curl command to install",
        command:
          "curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash",
      },
      {
        title: "Install Node Version",
        description: "Install specific Node version",
        command: "nvm install 18",
      },
    ],
    verified: true,
  },
  {
    id: "50",
    title: "PM2",
    description: "Install PM2 process manager for Node.js",
    category: "Tools",
    difficulty: "Intermediate",
    steps: [
      {
        title: "Install PM2",
        description: "Install globally",
        command: "npm install -g pm2",
      },
      {
        title: "Run App with PM2",
        description: "Start app with process management",
        command: "pm2 start app.js",
      },
    ],
    verified: true,
  },
  {
    id: "51",
    title: "MongoDB",
    description: "Install MongoDB Community Server for local database setup",
    category: "Database",
    difficulty: "Intermediate",
    steps: [
      {
        title: "Download MongoDB",
        description: "Get the installer for your OS from the official site",
        command:
          "# Download from https://www.mongodb.com/try/download/community",
      },
      {
        title: "Start MongoDB Service",
        description: "Run the MongoDB service on your system",
        command: "mongod --dbpath /data/db",
      },
      {
        title: "Verify Installation",
        description: "Check MongoDB version",
        command: "mongo --version",
      },
    ],
    verified: true,
  },
  {
    id: "52",
    title: "PostgreSQL",
    description: "Install PostgreSQL for relational database management",
    category: "Database",
    difficulty: "Intermediate",
    steps: [
      {
        title: "Download PostgreSQL",
        description: "Use the official installer or package manager",
        command: "# Download from https://www.postgresql.org/download/",
      },
      {
        title: "Start PostgreSQL",
        description: "Start the PostgreSQL service",
        command: "sudo service postgresql start",
      },
      {
        title: "Verify Installation",
        description: "Check version and connection",
        command: "psql --version",
      },
    ],
    verified: true,
  },
  {
    id: "53",
    title: "Firebase CLI",
    description: "Set up Firebase for web and mobile apps",
    category: "Cloud",
    difficulty: "Beginner",
    steps: [
      {
        title: "Install Firebase CLI",
        description: "Use npm to install globally",
        command: "npm install -g firebase-tools",
      },
      {
        title: "Login to Firebase",
        description: "Authenticate with your Google account",
        command: "firebase login",
      },
      {
        title: "Initialize Project",
        description: "Set up Firebase in your project folder",
        command: "firebase init",
      },
    ],
    verified: true,
  },
  {
    id: "54",
    title: "AWS CLI",
    description: "Install AWS Command Line Interface for managing AWS services",
    category: "Cloud",
    difficulty: "Intermediate",
    steps: [
      {
        title: "Install AWS CLI",
        description: "Use pip to install",
        command: "pip install awscli --upgrade --user",
      },
      {
        title: "Configure AWS CLI",
        description: "Set up your credentials",
        command: "aws configure",
      },
      {
        title: "Verify Installation",
        description: "Check AWS CLI version",
        command: "aws --version",
      },
    ],
    verified: true,
  },
  {
    id: "55",
    title: "Tailwind CSS",
    description: "Install Tailwind CSS for utility-first styling",
    category: "Frontend",
    difficulty: "Beginner",
    steps: [
      {
        title: "Install via npm",
        description: "Add Tailwind to your project",
        command:
          "npm install -D tailwindcss postcss autoprefixer\nnpx tailwindcss init -p",
      },
      {
        title: "Configure Template Paths",
        description: "Add your HTML/JS paths to `tailwind.config.js`",
        command: "content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}']",
      },
      {
        title: "Add Directives to CSS",
        description: "Add Tailwind layers in your CSS file",
        command: "@tailwind base;\n@tailwind components;\n@tailwind utilities;",
      },
    ],
    verified: true,
  },
  {
    id: "56",
    title: "TensorFlow",
    description: "Install TensorFlow for machine learning and AI projects",
    category: "AI/ML",
    difficulty: "Intermediate",
    steps: [
      {
        title: "Install via pip",
        description: "Install TensorFlow package",
        command: "pip install tensorflow",
      },
      {
        title: "Verify Installation",
        description: "Import TensorFlow and check version",
        command: 'python -c "import tensorflow as tf; print(tf.__version__)"',
      },
    ],
    verified: true,
  },
  {
    id: "57",
    title: "PyTorch",
    description: "Install PyTorch for deep learning development",
    category: "AI/ML",
    difficulty: "Intermediate",
    steps: [
      {
        title: "Install PyTorch",
        description: "Choose version and install using pip",
        command: "# Visit https://pytorch.org/get-started/locally/",
      },
      {
        title: "Verify Installation",
        description: "Import torch and print version",
        command: 'python -c "import torch; print(torch.__version__)"',
      },
    ],
    verified: true,
  },
  {
    id: "58",
    title: "MySQL",
    description: "Install MySQL database server",
    category: "Database",
    difficulty: "Intermediate",
    steps: [
      {
        title: "Install MySQL",
        description: "Use apt or installer",
        command: "sudo apt install mysql-server",
      },
      {
        title: "Secure Installation",
        description: "Run secure setup script",
        command: "sudo mysql_secure_installation",
      },
      {
        title: "Verify Connection",
        description: "Connect to MySQL shell",
        command: "mysql -u root -p",
      },
    ],
    verified: true,
  },
  {
    id: "59",
    title: "Redis",
    description: "Install Redis for caching and session storage",
    category: "Database",
    difficulty: "Intermediate",
    steps: [
      {
        title: "Install Redis",
        description: "Use apt or brew to install",
        command: "sudo apt install redis-server",
      },
      {
        title: "Start Redis Service",
        description: "Enable and start Redis",
        command: "sudo systemctl enable redis\nsudo systemctl start redis",
      },
      {
        title: "Test Connection",
        description: "Ping Redis to confirm it's running",
        command: "redis-cli ping",
      },
    ],
    verified: true,
  },
  {
    id: "60",
    title: "Vite",
    description: "Install Vite for blazing fast frontend development",
    category: "Frontend",
    difficulty: "Beginner",
    steps: [
      {
        title: "Create Vite App",
        description: "Use npm to scaffold a project",
        command: "npm create vite@latest my-app",
      },
      {
        title: "Install Dependencies",
        description: "Move to project and install dependencies",
        command: "cd my-app\nnpm install",
      },
      {
        title: "Start Dev Server",
        description: "Run local dev server",
        command: "npm run dev",
      },
    ],
    verified: true,
  },
  {
    id: "61",
    title: "Kubernetes (kubectl)",
    description: "Install kubectl for managing Kubernetes clusters",
    category: "DevOps",
    difficulty: "Advanced",
    steps: [
      {
        title: "Install kubectl",
        description: "Download and install kubectl CLI",
        command:
          "curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl\nchmod +x ./kubectl\nsudo mv ./kubectl /usr/local/bin/kubectl",
      },
      {
        title: "Verify Installation",
        description: "Check kubectl version",
        command: "kubectl version --client",
      },
    ],
    verified: true,
  },
  {
    id: "62",
    title: "Jupyter Notebook",
    description: "Install Jupyter Notebook for Python and Data Science",
    category: "AI/ML",
    difficulty: "Beginner",
    steps: [
      {
        title: "Install Jupyter",
        description: "Use pip to install Jupyter",
        command: "pip install notebook",
      },
      {
        title: "Run Notebook",
        description: "Start the Jupyter Notebook server",
        command: "jupyter notebook",
      },
    ],
    verified: true,
  },
  {
    id: "63",
    title: "OpenAI API",
    description: "Set up OpenAI API for AI text and image generation",
    category: "AI/ML",
    difficulty: "Intermediate",
    steps: [
      {
        title: "Install OpenAI Library",
        description: "Use pip to install OpenAI package",
        command: "pip install openai",
      },
      {
        title: "Set API Key",
        description: "Add your API key to environment variables",
        command: "export OPENAI_API_KEY='your-key-here'",
      },
      {
        title: "Test API",
        description: "Run a simple text completion test",
        command: "python -c \"import openai; print('✅ OpenAI Ready!')\"",
      },
    ],
    verified: true,
  },
];

export const projectsIdeas = [
  {
    id: "1",
    title: "Personal Portfolio Website",
    category: "Web Development",
    TechStack: "React, TypeScript, Tailwind CSS",
    level: "Beginner",
  },
  {
    id: "2",
    title: "To-Do List App",
    category: "Productivity",
    TechStack: "Vue.js, JavaScript, CSS",
    level: "Beginner",
  },
  {
    id: "3",
    title: "Blog Platform",
    category: "Content Management",
    TechStack: "Next.js, Node.js, MongoDB",
    level: "Intermediate",
  },
  {
    id: "4",
    title: "E-commerce Store",
    category: "Retail",
    TechStack: "Angular, Firebase, Stripe",
    level: "Advanced",
  },
  {
    id: "5",
    title: "Chat Application",
    category: "Communication",
    TechStack: "React Native, Socket.io, Express.js",
    level: "Intermediate",
  },
  {
    id: "6",
    title: "Weather App",
    category: "Utilities",
    TechStack: "Svelte, JavaScript, OpenWeatherMap API",
    level: "Beginner",
  },
  {
    id: "7",
    title: "Recipe Finder",
    category: "Lifestyle",
    TechStack: "React, Spoonacular API, CSS",
    level: "Beginner",
  },
  {
    id: "8",
    title: "Expense Tracker",
    category: "Finance",
    TechStack: "Vue, Firebase, Chart.js",
    level: "Intermediate",
  },
  {
    id: "9",
    title: "Fitness Tracker",
    category: "Health",
    TechStack: "React Native, Redux, Node.js",
    level: "Intermediate",
  },
  {
    id: "10",
    title: "Online Quiz App",
    category: "Education",
    TechStack: "React, TypeScript, Firebase",
    level: "Beginner",
  },
  {
    id: "11",
    title: "AI Image Generator",
    category: "AI & ML",
    TechStack: "Next.js, OpenAI API, Cloudinary",
    level: "Advanced",
  },
  {
    id: "12",
    title: "Music Player",
    category: "Entertainment",
    TechStack: "React, HTML5 Audio, Tailwind CSS",
    level: "Beginner",
  },
  {
    id: "13",
    title: "Video Streaming Platform",
    category: "Media",
    TechStack: "Node.js, React, AWS S3",
    level: "Advanced",
  },
  {
    id: "14",
    title: "Job Finder App",
    category: "Career",
    TechStack: "React, Express.js, MongoDB",
    level: "Intermediate",
  },
  {
    id: "15",
    title: "Language Learning Platform",
    category: "Education",
    TechStack: "Next.js, Prisma, PostgreSQL",
    level: "Advanced",
  },
  {
    id: "16",
    title: "Online Code Editor",
    category: "Development",
    TechStack: "React, Monaco Editor, Node.js",
    level: "Advanced",
  },
  {
    id: "17",
    title: "Task Management Dashboard",
    category: "Productivity",
    TechStack: "Vue, Tailwind, Firebase",
    level: "Intermediate",
  },
  {
    id: "18",
    title: "Virtual Whiteboard",
    category: "Collaboration",
    TechStack: "Canvas API, React, Socket.io",
    level: "Advanced",
  },
  {
    id: "19",
    title: "News Aggregator",
    category: "Media",
    TechStack: "React, News API, Vite",
    level: "Beginner",
  },
  {
    id: "20",
    title: "Online Poll System",
    category: "Engagement",
    TechStack: "React, Express.js, MongoDB",
    level: "Intermediate",
  },
  {
    id: "21",
    title: "Event Booking App",
    category: "Event Management",
    TechStack: "Angular, Firebase, Stripe",
    level: "Intermediate",
  },
  {
    id: "22",
    title: "Travel Journal",
    category: "Lifestyle",
    TechStack: "React, Firebase, Tailwind CSS",
    level: "Beginner",
  },
  {
    id: "23",
    title: "Crypto Tracker",
    category: "Finance",
    TechStack: "Next.js, CoinGecko API, Chart.js",
    level: "Intermediate",
  },
  {
    id: "24",
    title: "Online Resume Builder",
    category: "Tools",
    TechStack: "React, Node.js, PDFKit",
    level: "Intermediate",
  },
  {
    id: "25",
    title: "Stock Market Dashboard",
    category: "Finance",
    TechStack: "Vue, D3.js, Node.js",
    level: "Advanced",
  },
  {
    id: "26",
    title: "AI Chatbot",
    category: "AI & ML",
    TechStack: "Python, Flask, OpenAI API",
    level: "Advanced",
  },
  {
    id: "27",
    title: "Notes App with Tags",
    category: "Productivity",
    TechStack: "React, LocalStorage, Tailwind",
    level: "Beginner",
  },
  {
    id: "28",
    title: "Flashcards Learning App",
    category: "Education",
    TechStack: "Vue, Firebase, CSS",
    level: "Beginner",
  },
  {
    id: "29",
    title: "Online Forum",
    category: "Community",
    TechStack: "Next.js, Prisma, PostgreSQL",
    level: "Intermediate",
  },
  {
    id: "30",
    title: "Meme Generator",
    category: "Fun",
    TechStack: "React, Canvas API, Tailwind",
    level: "Beginner",
  },
  {
    id: "31",
    title: "Restaurant Finder",
    category: "Lifestyle",
    TechStack: "React, Yelp API, Mapbox",
    level: "Intermediate",
  },
  {
    id: "32",
    title: "Virtual Pet App",
    category: "Entertainment",
    TechStack: "React Native, Firebase",
    level: "Intermediate",
  },
  {
    id: "33",
    title: "File Sharing App",
    category: "Tools",
    TechStack: "Node.js, Express, AWS S3",
    level: "Advanced",
  },
  {
    id: "34",
    title: "Markdown Blog Editor",
    category: "Content Management",
    TechStack: "Next.js, MDX, Tailwind CSS",
    level: "Intermediate",
  },
  {
    id: "35",
    title: "Habit Tracker",
    category: "Productivity",
    TechStack: "React, IndexedDB, Tailwind",
    level: "Beginner",
  },
  {
    id: "36",
    title: "Portfolio CMS",
    category: "Development",
    TechStack: "Strapi, React, PostgreSQL",
    level: "Advanced",
  },
  {
    id: "37",
    title: "Photo Gallery",
    category: "Media",
    TechStack: "React, Firebase Storage, Tailwind",
    level: "Beginner",
  },
  {
    id: "38",
    title: "Online IDE",
    category: "Development",
    TechStack: "React, Docker, Node.js",
    level: "Advanced",
  },
  {
    id: "39",
    title: "E-learning Platform",
    category: "Education",
    TechStack: "Next.js, MongoDB, Stripe",
    level: "Advanced",
  },
  {
    id: "40",
    title: "Recipe Sharing Community",
    category: "Social",
    TechStack: "React, Firebase, Tailwind",
    level: "Intermediate",
  },
  {
    id: "41",
    title: "Travel Expense Splitter",
    category: "Finance",
    TechStack: "React, Context API, LocalStorage",
    level: "Beginner",
  },
  {
    id: "42",
    title: "Health Reminder App",
    category: "Health",
    TechStack: "Flutter, Firebase, Notifications API",
    level: "Intermediate",
  },
  {
    id: "43",
    title: "Smart Home Dashboard",
    category: "IoT",
    TechStack: "React, MQTT, Node.js",
    level: "Advanced",
  },
  {
    id: "44",
    title: "URL Shortener",
    category: "Tools",
    TechStack: "Express.js, MongoDB, React",
    level: "Intermediate",
  },
  {
    id: "45",
    title: "Donation Platform",
    category: "Charity",
    TechStack: "Next.js, Firebase, Razorpay",
    level: "Advanced",
  },
  {
    id: "46",
    title: "Blog Comment System",
    category: "Content",
    TechStack: "React, Node.js, PostgreSQL",
    level: "Intermediate",
  },
  {
    id: "47",
    title: "Real-time Collaboration Pad",
    category: "Collaboration",
    TechStack: "React, WebRTC, Socket.io",
    level: "Advanced",
  },
  {
    id: "48",
    title: "Quiz Battle Game",
    category: "Game",
    TechStack: "React, Node.js, Socket.io",
    level: "Intermediate",
  },
  {
    id: "49",
    title: "Online Photo Editor",
    category: "Design",
    TechStack: "React, Canvas API, Tailwind CSS",
    level: "Advanced",
  },
  {
    id: "50",
    title: "Typing Speed Test",
    category: "Game",
    TechStack: "React, TypeScript, Tailwind",
    level: "Beginner",
  },
  {
    id: "51",
    title: "AI Resume Analyzer",
    category: "AI & ML",
    TechStack: "Python, Flask, OpenAI API",
    level: "Advanced",
  },
  {
    id: "52",
    title: "Podcast Player App",
    category: "Media",
    TechStack: "React Native, Expo, Spotify API",
    level: "Intermediate",
  },
  {
    id: "53",
    title: "AR Furniture Preview",
    category: "AR/VR",
    TechStack: "Three.js, WebXR, React",
    level: "Advanced",
  },
  {
    id: "54",
    title: "Online Habit Coach",
    category: "Health",
    TechStack: "Next.js, Firebase, Tailwind CSS",
    level: "Intermediate",
  },
  {
    id: "55",
    title: "AI Study Assistant",
    category: "Education",
    TechStack: "OpenAI API, React, TypeScript",
    level: "Advanced",
  },
  {
    id: "56",
    title: "Daily Quote Generator",
    category: "Motivation",
    TechStack: "React, Random Quote API, CSS",
    level: "Beginner",
  },
  {
    id: "57",
    title: "Crypto News Tracker",
    category: "Finance",
    TechStack: "Next.js, CoinMarketCap API, Tailwind",
    level: "Intermediate",
  },
  {
    id: "58",
    title: "Workout Planner",
    category: "Health",
    TechStack: "React Native, Firebase",
    level: "Intermediate",
  },
  {
    id: "59",
    title: "Smart Expense Split App",
    category: "Finance",
    TechStack: "Vue, Node.js, MongoDB",
    level: "Intermediate",
  },
  {
    id: "60",
    title: "AI Writing Assistant",
    category: "AI & ML",
    TechStack: "Next.js, OpenAI API, Tailwind",
    level: "Advanced",
  },
  {
    id: "61",
    title: "Online Photo Compressor",
    category: "Tools",
    TechStack: "React, Browser Image Compression API",
    level: "Beginner",
  },
  {
    id: "62",
    title: "Travel Itinerary Planner",
    category: "Travel",
    TechStack: "React, Google Maps API, Tailwind",
    level: "Intermediate",
  },
  {
    id: "63",
    title: "Online Kanban Board",
    category: "Productivity",
    TechStack: "React, Drag-and-Drop, Firebase",
    level: "Intermediate",
  },
  {
    id: "64",
    title: "AI Voice Summarizer",
    category: "AI & ML",
    TechStack: "Python, Whisper, React",
    level: "Advanced",
  },
  {
    id: "65",
    title: "Event Countdown Timer",
    category: "Utilities",
    TechStack: "HTML, CSS, JavaScript",
    level: "Beginner",
  },
  {
    id: "66",
    title: "Smart Inventory Tracker",
    category: "Business",
    TechStack: "React, Node.js, MySQL",
    level: "Intermediate",
  },
  {
    id: "67",
    title: "Recipe Ingredients Scanner",
    category: "Lifestyle",
    TechStack: "Flutter, Firebase ML",
    level: "Advanced",
  },
  {
    id: "68",
    title: "Interactive 3D Portfolio",
    category: "Web Design",
    TechStack: "React Three Fiber, Tailwind",
    level: "Advanced",
  },
  {
    id: "69",
    title: "AI Interview Prep Bot",
    category: "AI & ML",
    TechStack: "Next.js, OpenAI, Firebase",
    level: "Advanced",
  },
  {
    id: "70",
    title: "Pet Adoption Platform",
    category: "Social Good",
    TechStack: "React, Node.js, MongoDB",
    level: "Intermediate",
  },
  {
    id: "71",
    title: "Voice-Controlled Notes App",
    category: "Accessibility",
    TechStack: "React, SpeechRecognition API",
    level: "Intermediate",
  },
  {
    id: "72",
    title: "Budget Calculator",
    category: "Finance",
    TechStack: "Vue.js, Tailwind CSS",
    level: "Beginner",
  },
  {
    id: "73",
    title: "Online Meme Community",
    category: "Social",
    TechStack: "Next.js, Prisma, PostgreSQL",
    level: "Intermediate",
  },
  {
    id: "74",
    title: "AI Travel Recommender",
    category: "AI & ML",
    TechStack: "Python, Flask, ML Model",
    level: "Advanced",
  },
  {
    id: "75",
    title: "Stock Alert System",
    category: "Finance",
    TechStack: "Node.js, Twilio API, MongoDB",
    level: "Advanced",
  },
  {
    id: "76",
    title: "Podcast Transcription Tool",
    category: "Media",
    TechStack: "React, Whisper API",
    level: "Intermediate",
  },
  {
    id: "77",
    title: "Portfolio Analytics Dashboard",
    category: "Web Tools",
    TechStack: "Next.js, Chart.js, Firebase",
    level: "Intermediate",
  },
  {
    id: "78",
    title: "Language Translator App",
    category: "AI & ML",
    TechStack: "Python, HuggingFace API",
    level: "Advanced",
  },
  {
    id: "79",
    title: "Music Playlist Generator",
    category: "Entertainment",
    TechStack: "React, Spotify API",
    level: "Intermediate",
  },
  {
    id: "80",
    title: "Productivity Timer",
    category: "Utilities",
    TechStack: "React, CSS Animations",
    level: "Beginner",
  },
  {
    id: "81",
    title: "AI Email Sorter",
    category: "AI & ML",
    TechStack: "Python, Gmail API, TensorFlow",
    level: "Advanced",
  },
  {
    id: "82",
    title: "Online Auction App",
    category: "E-commerce",
    TechStack: "React, Express, MongoDB",
    level: "Intermediate",
  },
  {
    id: "83",
    title: "Smart File Organizer",
    category: "Automation",
    TechStack: "Python, Tkinter",
    level: "Intermediate",
  },
  {
    id: "84",
    title: "Virtual Study Room",
    category: "Education",
    TechStack: "React, WebRTC, Firebase",
    level: "Advanced",
  },
  {
    id: "85",
    title: "Donation Tracker",
    category: "Social Good",
    TechStack: "Next.js, Firebase, Stripe",
    level: "Intermediate",
  },
  {
    id: "86",
    title: "AI Color Palette Generator",
    category: "Design",
    TechStack: "React, OpenAI API",
    level: "Intermediate",
  },
  {
    id: "87",
    title: "Smart Reminder Bot",
    category: "Automation",
    TechStack: "Node.js, Telegram API",
    level: "Intermediate",
  },
  {
    id: "88",
    title: "Eco Footprint Calculator",
    category: "Environment",
    TechStack: "React, D3.js",
    level: "Intermediate",
  },
  {
    id: "89",
    title: "Freelancer Marketplace",
    category: "Business",
    TechStack: "Next.js, Prisma, PostgreSQL",
    level: "Advanced",
  },
  {
    id: "90",
    title: "AI Resume Builder",
    category: "AI & ML",
    TechStack: "Next.js, OpenAI API, Tailwind",
    level: "Advanced",
  },
  {
    id: "91",
    title: "Food Delivery Clone",
    category: "Delivery",
    TechStack: "React Native, Firebase",
    level: "Intermediate",
  },
  {
    id: "92",
    title: "Personal Finance Dashboard",
    category: "Finance",
    TechStack: "Vue.js, Chart.js, Node.js",
    level: "Intermediate",
  },
  {
    id: "93",
    title: "AI-Powered PDF Q&A",
    category: "AI & ML",
    TechStack: "Next.js, LangChain, OpenAI API",
    level: "Advanced",
  },
  {
    id: "94",
    title: "Smart Home Controller",
    category: "IoT",
    TechStack: "React, MQTT, Raspberry Pi",
    level: "Advanced",
  },
  {
    id: "95",
    title: "Collaborative Code Snippet Hub",
    category: "Development",
    TechStack: "Next.js, Firebase",
    level: "Intermediate",
  },
  {
    id: "96",
    title: "Virtual Art Gallery",
    category: "Design",
    TechStack: "React Three Fiber, Tailwind",
    level: "Advanced",
  },
  {
    id: "97",
    title: "Online Typing Tutor",
    category: "Education",
    TechStack: "React, Tailwind, LocalStorage",
    level: "Beginner",
  },
  {
    id: "98",
    title: "AI Movie Recommender",
    category: "AI & ML",
    TechStack: "Python, Scikit-learn, Flask",
    level: "Advanced",
  },
  {
    id: "99",
    title: "Community Events Map",
    category: "Social",
    TechStack: "React, Leaflet.js, Firebase",
    level: "Intermediate",
  },
  {
    id: "100",
    title: "Gamified Learning Platform",
    category: "Education",
    TechStack: "Next.js, Prisma, Tailwind",
    level: "Advanced",
  },
  {
    id: "101",
    title: "AI Image Generator",
    category: "Artificial Intelligence",
    TechStack: "Next.js, OpenAI API, Tailwind CSS",
    level: "Advanced",
  },
  {
    id: "102",
    title: "Crypto Dashboard",
    category: "Finance",
    TechStack: "React, Chart.js, CoinGecko API",
    level: "Intermediate",
  },
  {
    id: "103",
    title: "Online Code Editor",
    category: "Developer Tools",
    TechStack: "React, Monaco Editor, Node.js",
    level: "Advanced",
  },
  {
    id: "104",
    title: "Recipe Finder App",
    category: "Lifestyle",
    TechStack: "Vue.js, Spoonacular API, CSS",
    level: "Beginner",
  },
  {
    id: "105",
    title: "Fitness Tracker",
    category: "Health",
    TechStack: "React Native, Firebase, Redux",
    level: "Intermediate",
  },
  {
    id: "106",
    title: "Stock Market Simulator",
    category: "Finance",
    TechStack: "Angular, Node.js, PostgreSQL",
    level: "Advanced",
  },
  {
    id: "107",
    title: "Task Automation Bot",
    category: "Productivity",
    TechStack: "Python, Selenium, Tkinter",
    level: "Intermediate",
  },
  {
    id: "108",
    title: "AI Resume Analyzer",
    category: "AI & ML",
    TechStack: "Flask, OpenAI API, Tailwind",
    level: "Advanced",
  },
  {
    id: "109",
    title: "Virtual Study Room",
    category: "Education",
    TechStack: "Next.js, WebRTC, Socket.io",
    level: "Advanced",
  },
  {
    id: "110",
    title: "Language Translator App",
    category: "Utilities",
    TechStack: "React, Google Translate API",
    level: "Intermediate",
  },
  {
    id: "111",
    title: "Expense Splitter",
    category: "Finance",
    TechStack: "React, Context API, CSS",
    level: "Beginner",
  },
  {
    id: "112",
    title: "AI Chatbot",
    category: "Communication",
    TechStack: "Python, Flask, OpenAI API",
    level: "Advanced",
  },
  {
    id: "113",
    title: "Movie Recommendation System",
    category: "Entertainment",
    TechStack: "Python, Pandas, Streamlit",
    level: "Intermediate",
  },
  {
    id: "114",
    title: "Book Reading Tracker",
    category: "Lifestyle",
    TechStack: "Vue.js, Firebase, Tailwind",
    level: "Beginner",
  },
  {
    id: "115",
    title: "Job Board Platform",
    category: "Career",
    TechStack: "Next.js, Prisma, PostgreSQL",
    level: "Advanced",
  },
  {
    id: "116",
    title: "Travel Planner",
    category: "Travel",
    TechStack: "React, Google Maps API, CSS",
    level: "Intermediate",
  },
  {
    id: "117",
    title: "Online Poll System",
    category: "Community",
    TechStack: "Angular, Node.js, MongoDB",
    level: "Intermediate",
  },
  {
    id: "118",
    title: "Music Player",
    category: "Entertainment",
    TechStack: "React, Redux, Spotify API",
    level: "Intermediate",
  },
  {
    id: "119",
    title: "Real-Time Collaboration Notes",
    category: "Productivity",
    TechStack: "Next.js, Firebase, WebSockets",
    level: "Advanced",
  },
  {
    id: "120",
    title: "E-learning Dashboard",
    category: "Education",
    TechStack: "React, Node.js, MongoDB",
    level: "Intermediate",
  },
  {
    id: "121",
    title: "Pet Adoption Platform",
    category: "Social Good",
    TechStack: "Vue.js, Firebase, Tailwind",
    level: "Beginner",
  },
  {
    id: "122",
    title: "AI Text Summarizer",
    category: "AI & ML",
    TechStack: "Python, Transformers, Flask",
    level: "Advanced",
  },
  {
    id: "123",
    title: "Podcast Manager",
    category: "Media",
    TechStack: "Next.js, RSS Parser, Tailwind",
    level: "Intermediate",
  },
  {
    id: "124",
    title: "Smart Calendar",
    category: "Productivity",
    TechStack: "React, FullCalendar.js, Redux",
    level: "Intermediate",
  },
  {
    id: "125",
    title: "Portfolio CMS",
    category: "Web Tools",
    TechStack: "Next.js, Sanity CMS, Tailwind",
    level: "Advanced",
  },
  {
    id: "126",
    title: "E-voting System",
    category: "Security",
    TechStack: "React, Solidity, Ethereum",
    level: "Advanced",
  },
  {
    id: "127",
    title: "Online Quiz Generator",
    category: "Education",
    TechStack: "React, Firebase, Tailwind",
    level: "Beginner",
  },
  {
    id: "128",
    title: "AI Voice Assistant",
    category: "AI & ML",
    TechStack: "Python, SpeechRecognition, Flask",
    level: "Advanced",
  },
  {
    id: "129",
    title: "Habit Tracker",
    category: "Health",
    TechStack: "React, LocalStorage, CSS",
    level: "Beginner",
  },
  {
    id: "130",
    title: "Smart Home Dashboard",
    category: "IoT",
    TechStack: "Next.js, MQTT, Node.js",
    level: "Advanced",
  },
  {
    id: "131",
    title: "Blog Comment Analyzer",
    category: "AI & NLP",
    TechStack: "Python, NLTK, Flask",
    level: "Intermediate",
  },
  {
    id: "132",
    title: "Restaurant Reservation App",
    category: "Hospitality",
    TechStack: "React, Node.js, MongoDB",
    level: "Intermediate",
  },
  {
    id: "133",
    title: "Online Whiteboard",
    category: "Collaboration",
    TechStack: "Canvas API, React, WebSockets",
    level: "Advanced",
  },
  {
    id: "134",
    title: "Video Streaming Platform",
    category: "Media",
    TechStack: "Next.js, Node.js, AWS S3",
    level: "Advanced",
  },
  {
    id: "135",
    title: "AI Interview Practice Bot",
    category: "Career",
    TechStack: "Python, OpenAI API, Streamlit",
    level: "Advanced",
  },
  {
    id: "136",
    title: "Plant Care Reminder",
    category: "Lifestyle",
    TechStack: "React Native, Expo, Firebase",
    level: "Beginner",
  },
  {
    id: "137",
    title: "Smart Expense Tracker",
    category: "Finance",
    TechStack: "Next.js, Chart.js, Prisma",
    level: "Intermediate",
  },
  {
    id: "138",
    title: "Virtual Art Gallery",
    category: "Art & Design",
    TechStack: "Three.js, React, Tailwind",
    level: "Advanced",
  },
  {
    id: "139",
    title: "AI Grammar Checker",
    category: "AI & NLP",
    TechStack: "Python, Transformers, Flask",
    level: "Advanced",
  },
  {
    id: "140",
    title: "Crowdfunding Platform",
    category: "Finance",
    TechStack: "React, Solidity, Web3.js",
    level: "Advanced",
  },
  {
    id: "141",
    title: "Donation Tracker",
    category: "Charity",
    TechStack: "Vue.js, Firebase, Tailwind",
    level: "Beginner",
  },
  {
    id: "142",
    title: "Crypto Price Notifier",
    category: "Finance",
    TechStack: "React, CoinMarketCap API, CSS",
    level: "Intermediate",
  },
  {
    id: "143",
    title: "AI Music Composer",
    category: "AI & ML",
    TechStack: "Python, Magenta, Flask",
    level: "Advanced",
  },
  {
    id: "144",
    title: "Language Learning App",
    category: "Education",
    TechStack: "React, Node.js, PostgreSQL",
    level: "Intermediate",
  },
  {
    id: "145",
    title: "Digital Business Card",
    category: "Web Tools",
    TechStack: "Next.js, Tailwind, QR Code API",
    level: "Beginner",
  },
  {
    id: "146",
    title: "Virtual Internship Portal",
    category: "Career",
    TechStack: "React, Express.js, MongoDB",
    level: "Intermediate",
  },
  {
    id: "147",
    title: "AI Meme Generator",
    category: "Entertainment",
    TechStack: "Next.js, OpenAI API, Tailwind",
    level: "Advanced",
  },
  {
    id: "148",
    title: "Smart Notes Organizer",
    category: "Productivity",
    TechStack: "React, Firebase, Tailwind",
    level: "Intermediate",
  },
  {
    id: "149",
    title: "Gamified Habit Builder",
    category: "Health",
    TechStack: "React, Framer Motion, Redux",
    level: "Intermediate",
  },
  {
    id: "150",
    title: "Community Forum App",
    category: "Social",
    TechStack: "Next.js, Prisma, Supabase",
    level: "Advanced",
  },
];
